[package]
name = "auxlua"
version = "0.1.0"
authors = ["Y0SH1M4S73R <legoboyo@earthlink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = {git = "https://github.com/willox/auxtools"}
mlua = {version = "0.7.3", features = ["lua54", "vendored"]}
globals = "1"